# Generated by Django 5.1.3 on 2025-01-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_details',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
