# Generated by Django 5.1.3 on 2025-01-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='badge',
        ),
    ]
