# Generated by Django 5.1.3 on 2025-01-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_remove_membership_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='price_per_session',
        ),
    ]
