# Generated by Django 5.1.3 on 2025-01-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_membership_id_membershippurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippurchase',
            name='updated_at',
        ),
    ]
