# Generated by Django 5.1.3 on 2025-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
