# Generated by Django 5.1.3 on 2025-01-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plans', '0002_workoutplan_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutPlan_details',
        ),
    ]
